<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="stylesheets/pygment_trac.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="stylesheets/print.css" media="print" />

    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <title>Dongyuhao.github.io by dongyuhao</title>
      <style type="text/css">
          .auto-style1 {
              position:absolute;
              width: 220px;
              height: 220px;
              top: 244px;
              margin:5px;
              text-align:center;
                background: #2e7bcf url(../images/header-bg.jpg) 0 0 repeat-x;
          }
          .auto-style2 {
              position: absolute;
              width: 220px;
              height: 220px;
              left: 462px;
              top: 244px;
                    margin:5px;
                    text-align:center;
                      background: #2e7bcf url(../images/header-bg.jpg) 0 0 repeat-x;
          }
          .auto-style3 {
              position: absolute;
              width: 220px;
              height: 220px;
              left: 231px;
              top: 244px;
              right: 479px;
                    margin:5px;
                    text-align:center;
                      background: #2e7bcf url(../images/header-bg.jpg) 0 0 repeat-x;
          }
          .rukouname {
                font-family: 'Architects Daughter', 'Helvetica Neue', Helvetica, Arial, serif; 
            font-size: 24px;
            color: #fff;
          }
          .blue {
          
          }
        
      </style>
  </head>

  <body>
    <header>
      <div class="inner">
        <h1>Dongyuhao.github.io</h1>
        <h2>fish</h2>
        <a href="https://github.com/dongyuhao" class="button"><small>Follow me on</small>GitHub</a>
      </div>
    </header>

    <div id="content-wrapper">
      <div class="inner clearfix" style="left: 0px; top: 0px; height: 530px">
        <section id="main-content">
          <h3>
<a name="welcome-to-github-pages" class="anchor" href="#welcome-to-github-pages"><span class="octicon octicon-link"></span></a>Welcome to GitHub Pages.</h3>

<pre><code>if(you>0)
{ 
   console.log("hello world");
}
</code></pre>

<h3>
<a name="designer-templates" class="anchor" href="dongyuhao.github.io/coolfish"><span class="octicon octicon-link"></span></a>My Home Page</h3>
 <div class="auto-style2">
    <div class="rukouname" style="padding:20%">My Website</br>
        <button class="blue">进入</button><a class="button">123</a>
    </div>
     </div>
            <div class="auto-style1">My Resume</div>
            <div class="auto-style3">My Resume(HTML5)</div>
        </section>

         
        <aside id="sidebar">
            最新日志：</br>
            <a>XXXXX</a>

          
        </aside>
      </div>
    </div>

  <div class="footer">By Coolfish<p>This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the Architect theme by <a href="https://twitter.com/jasonlong">Jason Long</a>.</p></div>
  </body>
</html>